const express = require('express');
const router = express.Router();
const partidoController = require('../controllers/partidoController');
const { upload } = require('../config/multer');

router.post('/insert', partidoController.createPartido);
router.post('/submitResultados', upload.single('imagenPlanilla'), partidoController.submitResultados);
router.get('/select/:categoriaId/:campeonatoId', partidoController.getPartidosByCategoriaId);
router.get('/selectPartidosById/:EquipoId/:campeonatoId', partidoController.getPartidosByEquipoId);
router.get('/get_upcoming_matches/:categoria/:CampeonatoId', partidoController.getUpcomingMatchesByCategoria);
router.get('/get_past_matches/:categoria/:CampeonatoId', partidoController.getPastMatchesByCategoria);
router.get('/get_all_matchesUpcoming/:categoria/:CampeonatoId', partidoController.getAllMatchesExceptUpcoming);
router.get('/get_all_matchesPast/:categoria/:CampeonatoId', partidoController.getAllMatchesExceptPrevious);
router.get('/:id', partidoController.getPartidoById);
router.put('/edit/:id', partidoController.updatePartido);
router.put('/delete/:id', partidoController.deletePartido);
router.get('/get_partido_completo/:partidoId', partidoController.getPartidoCompletoById);
router.get('/get_jugadores/:equipoId/campeonato/:campeonatoId', partidoController.getJugadoresByEquipoId);
router.get('/get_arbitros/:partidoId', partidoController.getArbitrosByPartidoId);
router.get('/partidos_pdf/filtrar', partidoController.getPartidosByLugarYFecha);
router.get('/partidos_pdf/filtrar_fecha', partidoController.getPartidosByFecha);
router.get('/generar-fixture/:campeonatoId/:categoriaId', partidoController.generarFixture);
router.get('/generar-fixture-con-fechas/:campeonatoId/:categoriaId', partidoController.generarFixtureConFechas);
router.get('/generar-fixture-completo/:campeonatoId/:categoriaId', partidoController.generarFixtureCompleto);
router.post('/registrar-partidos/:campeonatoId/:categoriaId', partidoController.registrarPartidos);
router.get('/campeonatoPartidosPDF/:campeonatoId', partidoController.getPartidosByCampeonato);
router.get('/reprogramar-partido/:partidoId', partidoController.reprogramarPartidoController);
router.post('/confirmar-reprogramacion', partidoController.confirmarReprogramacionPartidoController);
router.get('/resultados/:partidoId', partidoController.obtenerResultadosPartidoController);
router.get('/ganador/:partidoId', partidoController.obtenerGanadorPartido);
router.get('/fechas-disponibles/:lugar_id', partidoController.getFechasDisponiblesPorLugar);
router.get('/horarios-disponibles/:lugar_id/:fecha', partidoController.getHorariosDisponiblesPorFechaYLugar);
router.get('/arbitros-disponibles/:fecha/:hora/:lugar_id', partidoController.getArbitrosDisponiblesPorFechaYLugar);
router.post('/updateParcialResultados', partidoController.updateParcialResultados);
router.get('/marcadores-vivos/:campeonatoId/:categoriaId', partidoController.getMarcadoresVivos);
router.post('/update', partidoController.updatePartidoReal);
router.get('/verificar-fixture/:campeonatoId/:categoriaId', partidoController.verificarFixtureCompleto);

module.exports = router;
